import { JobRecord } from '@/types/jobs';
import { ScraperRun, ScraperHealth, HealingEvent } from '@/types/scraper';
import { calculateRiskScore } from '@/lib/risk-engine/scoring';
import { annotateDuplicates } from '@/lib/duplicate-detector/similarity';

const rawJobs = [
  // LOW RISK - Real-seeming jobs
  {
    title: 'Senior Software Engineer',
    companyName: 'Google',
    location: 'Mountain View, CA',
    description: 'We are looking for a Senior Software Engineer to join our Cloud Platform team. You will design and build scalable distributed systems, work with Kubernetes and GCP, and collaborate with cross-functional teams. Requirements: 5+ years of experience in backend development, proficiency in Go or Java, experience with cloud infrastructure.',
    applicationUrl: 'https://careers.google.com/jobs/results/123456/',
    salary: '$180,000 - $250,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-15',
    sourceName: 'Google Careers',
    sourceUrl: 'https://careers.google.com',
    companyUrl: 'https://about.google',
    skills: 'Go,Java,Kubernetes,GCP,Distributed Systems',
    remoteStatus: 'Hybrid',
  },
  {
    title: 'Product Manager',
    companyName: 'Microsoft',
    location: 'Redmond, WA',
    description: 'Microsoft is hiring a Product Manager for the Azure AI Platform. You will drive product strategy, define roadmaps, and work closely with engineering teams to deliver AI-powered solutions. Must have 3+ years of product management experience and strong technical background.',
    applicationUrl: 'https://careers.microsoft.com/us/en/job/MSR-123456',
    salary: '$145,000 - $200,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-14',
    sourceName: 'Microsoft Careers',
    sourceUrl: 'https://careers.microsoft.com',
    companyUrl: 'https://microsoft.com',
    skills: 'Product Management,AI,Azure,Strategy',
    remoteStatus: 'Hybrid',
  },
  {
    title: 'UX Designer',
    companyName: 'Spotify',
    location: 'New York, NY',
    description: 'Join Spotify as a UX Designer working on our mobile listening experience. You will conduct user research, create wireframes and prototypes, and collaborate with product and engineering. Portfolio required.',
    applicationUrl: 'https://lifeatspotify.com/jobs/ux-designer-123',
    salary: '$120,000 - $160,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-13',
    sourceName: 'Spotify Careers',
    sourceUrl: 'https://lifeatspotify.com',
    companyUrl: 'https://spotify.com',
    skills: 'UX Design,Figma,User Research,Prototyping',
    remoteStatus: 'Remote',
  },
  {
    title: 'Data Analyst',
    companyName: 'Netflix',
    location: 'Los Gatos, CA',
    description: 'Netflix seeks a Data Analyst to support content strategy through data-driven insights. Responsibilities include building dashboards, running A/B tests, and presenting findings to leadership. SQL, Python, and Tableau proficiency required.',
    applicationUrl: 'https://jobs.netflix.com/data-analyst-456',
    salary: '$130,000 - $180,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-12',
    sourceName: 'Netflix Careers',
    sourceUrl: 'https://jobs.netflix.com',
    companyUrl: 'https://netflix.com',
    skills: 'SQL,Python,Tableau,Data Analysis,Statistics',
    remoteStatus: 'On-site',
  },
  {
    title: 'DevOps Engineer',
    companyName: 'Amazon',
    location: 'Seattle, WA',
    description: 'Amazon Web Services is hiring a DevOps Engineer to manage cloud infrastructure for our enterprise customers. You will work with AWS services, Terraform, and CI/CD pipelines. 4+ years of DevOps experience required.',
    applicationUrl: 'https://amazon.jobs/devops-engineer-789',
    salary: '$155,000 - $210,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-11',
    sourceName: 'Amazon Jobs',
    sourceUrl: 'https://amazon.jobs',
    companyUrl: 'https://amazon.com',
    skills: 'AWS,Terraform,CI/CD,Docker,Kubernetes',
    remoteStatus: 'Hybrid',
  },
  {
    title: 'Frontend Developer',
    companyName: 'Shopify',
    location: 'Ottawa, Canada',
    description: 'Shopify is looking for a Frontend Developer to build merchant-facing tools. You will work with React, TypeScript, and our Polaris design system. Strong understanding of web accessibility and performance optimization needed.',
    applicationUrl: 'https://shopify.com/careers/frontend-012',
    salary: '$115,000 - $155,000 CAD',
    employmentType: 'Full-time',
    postedDate: '2026-08-10',
    sourceName: 'Shopify Careers',
    sourceUrl: 'https://shopify.com/careers',
    companyUrl: 'https://shopify.com',
    skills: 'React,TypeScript,Polaris,Accessibility',
    remoteStatus: 'Remote',
  },
  {
    title: 'Machine Learning Engineer',
    companyName: 'Meta',
    location: 'Menlo Park, CA',
    description: 'Meta AI is seeking a Machine Learning Engineer to work on large language models and recommendation systems. PhD or MS in CS/ML preferred. Experience with PyTorch, distributed training, and model optimization.',
    applicationUrl: 'https://metacareers.com/ml-engineer-345',
    salary: '$190,000 - $280,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-09',
    sourceName: 'Meta Careers',
    sourceUrl: 'https://metacareers.com',
    companyUrl: 'https://meta.com',
    skills: 'PyTorch,Machine Learning,NLP,Distributed Systems',
    remoteStatus: 'Hybrid',
  },
  {
    title: 'Technical Writer',
    companyName: 'Stripe',
    location: 'San Francisco, CA',
    description: 'Stripe is hiring a Technical Writer to create documentation for our payments platform APIs. You will write tutorials, API references, and integration guides. Experience with developer documentation and understanding of payment systems preferred.',
    applicationUrl: 'https://stripe.com/jobs/tw-678',
    salary: '$110,000 - $145,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-08',
    sourceName: 'Stripe Careers',
    sourceUrl: 'https://stripe.com/jobs',
    companyUrl: 'https://stripe.com',
    skills: 'Technical Writing,API Documentation,Markdown',
    remoteStatus: 'Remote',
  },
  // MEDIUM RISK - Some concerns
  {
    title: 'Digital Marketing Specialist',
    companyName: 'GrowthForce Digital',
    location: 'Remote',
    description: 'Fast-growing startup needs a Digital Marketing Specialist. Manage social media, create content, run paid campaigns. Must have experience with Google Ads and Facebook Ads Manager. Flexible hours, work from home opportunity.',
    applicationUrl: 'https://growthforcedigital.com/careers/marketing',
    salary: '$55,000 - $75,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-14',
    sourceName: 'Indeed',
    companyUrl: 'https://growthforcedigital.com',
    skills: 'Marketing,Social Media,Google Ads,Content Creation',
    remoteStatus: 'Remote',
  },
  {
    title: 'Customer Support Representative',
    companyName: 'TechFlow Solutions',
    location: 'Austin, TX',
    description: 'Looking for a friendly customer support representative to handle inquiries via phone and email. No experience necessary, we provide full training. Great opportunity for career growth. Excellent compensation package.',
    applicationUrl: 'https://techflow.solutions/apply',
    salary: '$35,000 - $45,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-13',
    sourceName: 'Indeed',
    skills: 'Customer Service,Communication',
    remoteStatus: 'Hybrid',
  },
  {
    title: 'Business Development Associate',
    companyName: 'NexGen Partners',
    location: 'Chicago, IL',
    description: 'Join our team as a Business Development Associate. Responsibilities include prospecting, cold calling, and building client relationships. Self-motivated individuals who thrive in a fast-paced environment will succeed here.',
    applicationUrl: 'https://nexgenpartners.com/jobs/bda',
    salary: '$50,000 - $80,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-12',
    sourceName: 'LinkedIn',
    skills: 'Sales,Business Development,Communication',
    remoteStatus: 'On-site',
  },
  {
    title: 'Content Creator',
    companyName: 'ViralMedia Inc',
    location: 'Remote',
    description: 'We are looking for a creative Content Creator to produce viral social media content. Must be able to create 5-10 pieces of content daily. Experience with TikTok, Instagram Reels, and YouTube Shorts. Great opportunity with unlimited growth potential.',
    applicationUrl: 'https://viralmedia.com/apply-now',
    salary: '$40,000 - $60,000',
    employmentType: 'Contract',
    postedDate: '2026-08-11',
    sourceName: 'Indeed',
    companyUrl: 'https://viralmedia.com',
    skills: 'Content Creation,Social Media,Video Editing',
    remoteStatus: 'Remote',
  },
  // HIGH RISK - Obviously scammy
  {
    title: 'Work From Home Data Entry - $500/Day!',
    companyName: '',
    location: 'Remote',
    description: 'URGENT! We need someone to do simple data entry work from home. Pay is $500 per day guaranteed. No experience needed. You just need a computer and internet. Pay a small registration fee of $50 to get started. Contact me on WhatsApp at +1-555-0123. Send your social security number for tax purposes.',
    applicationUrl: 'https://bit.ly/workfromhome-jobs',
    salary: '$500/day guaranteed',
    employmentType: 'Part-time',
    postedDate: '2026-08-15',
    sourceName: 'Craigslist',
    skills: 'Data Entry',
    remoteStatus: 'Remote',
  },
  {
    title: 'Immediate Start - Remote Administrative Assistant',
    companyName: 'Pacific Holdings LLC',
    location: 'Remote',
    description: 'Act now! Immediate start for Remote Administrative Assistant. $3,000 per week. We send you a check, you deposit it and send the difference via Western Union. This is legitimate work. Contact me on telegram @pac_holdings_hr. You will need your bank account number and routing number to receive payments.',
    applicationUrl: 'https://tinyurl.com/admin-jobs-2026',
    salary: '$3,000/week',
    employmentType: 'Part-time',
    postedDate: '2026-08-14',
    sourceName: 'Craigslist',
    skills: 'Administrative',
    remoteStatus: 'Remote',
  },
  {
    title: 'Investment Opportunity - Financial Advisor',
    companyName: 'Global Wealth Partners',
    location: 'Remote',
    description: 'Make money fast! Join our team of financial advisors. No experience needed. You will help clients invest in cryptocurrency and forex. High pay daily. Easy money. Just make an initial investment of $1,000 and watch it grow. Send money via bitcoin to get started. Guaranteed income of $5,000 per month.',
    applicationUrl: 'https://goo.gl/wealth-jobs',
    salary: '$5,000+/month guaranteed',
    employmentType: 'Full-time',
    postedDate: '2026-08-13',
    sourceName: 'Social Media',
    skills: 'Finance',
    remoteStatus: 'Remote',
  },
  {
    title: 'Package Handling Position - $400/Day',
    companyName: 'QuickShip Logistics',
    location: 'Multiple Locations',
    description: 'Join QuickShip Logistics as a Package Handler. $400 per day. Work flexible hours. Registration fee of $75 required. You will receive packages at your home and forward them. Text me at 555-9876. Unlimited earning potential. No interview needed.',
    applicationUrl: 'https://t.me/quickship_jobs',
    salary: '$400/day',
    employmentType: 'Part-time',
    postedDate: '2026-08-12',
    sourceName: 'Facebook',
    skills: 'Logistics',
    remoteStatus: 'Remote',
  },
  {
    title: 'Remote Software Tester - Easy Work',
    companyName: 'TestTech Global',
    location: 'Remote',
    description: 'Great opportunity to earn money by testing apps. Pay is $200 per test. We need your ID number and credit card details for verification. Pay a processing fee of $100. Call me at 555-1111. No experience needed. Earn money fast.',
    applicationUrl: 'http://suspicious-test-jobs.xyz/apply',
    salary: '$200/test',
    employmentType: 'Contract',
    postedDate: '2026-08-11',
    sourceName: 'Social Media',
    skills: 'Testing',
    remoteStatus: 'Remote',
  },
  // More varied jobs
  {
    title: 'Junior Python Developer',
    companyName: 'DataBricks',
    location: 'San Francisco, CA',
    description: 'DataBricks is looking for a Junior Python Developer to work on our data lakehouse platform. You will write Python code for data processing pipelines, write unit tests, and participate in code reviews. Knowledge of PySpark and SQL is a plus.',
    applicationUrl: 'https://databricks.com/careers/jr-python-123',
    salary: '$100,000 - $135,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-10',
    sourceName: 'LinkedIn',
    companyUrl: 'https://databricks.com',
    skills: 'Python,PySpark,SQL,Data Engineering',
    remoteStatus: 'Hybrid',
  },
  {
    title: 'Security Engineer',
    companyName: 'CrowdStrike',
    location: 'Austin, TX',
    description: 'CrowdStrike is hiring a Security Engineer to join our threat intelligence team. You will analyze malware, develop detection rules, and respond to incidents. CISSP or equivalent certification preferred. 3+ years of experience in cybersecurity.',
    applicationUrl: 'https://crowdstrike.com/careers/sec-eng-456',
    salary: '$140,000 - $190,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-09',
    sourceName: 'CrowdStrike Careers',
    companyUrl: 'https://crowdstrike.com',
    skills: 'Cybersecurity,Malware Analysis,Incident Response,CISSP',
    remoteStatus: 'Remote',
  },
  {
    title: 'iOS Developer',
    companyName: 'Apple',
    location: 'Cupertino, CA',
    description: 'Apple is seeking an iOS Developer to work on the next generation of health and fitness features. You will build Swift/SwiftUI applications, collaborate with designers, and optimize for performance. Experience with HealthKit and CoreMotion is a plus.',
    applicationUrl: 'https://jobs.apple.com/ios-dev-789',
    salary: '$165,000 - $230,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-08',
    sourceName: 'Apple Careers',
    companyUrl: 'https://apple.com',
    skills: 'Swift,SwiftUI,HealthKit,iOS Development',
    remoteStatus: 'On-site',
  },
  {
    title: 'Technical Support Engineer',
    companyName: 'Cloudflare',
    location: 'Austin, TX',
    description: 'Cloudflare needs a Technical Support Engineer to help enterprise customers with DNS, CDN, and security product issues. You will troubleshoot complex networking problems and write technical documentation. CCNA or networking experience preferred.',
    applicationUrl: 'https://cloudflare.com/careers/tse-012',
    salary: '$85,000 - $115,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-07',
    sourceName: 'Cloudflare Careers',
    companyUrl: 'https://cloudflare.com',
    skills: 'Networking,DNS,CDN,Technical Support',
    remoteStatus: 'Remote',
  },
  {
    title: 'Backend Engineer',
    companyName: 'Stripe',
    location: 'San Francisco, CA',
    description: 'Stripe is hiring a Backend Engineer to build reliable payment infrastructure. You will work with Ruby, Java, and Go to build APIs that process billions of dollars. Strong understanding of distributed systems and database design required.',
    applicationUrl: 'https://stripe.com/jobs/backend-345',
    salary: '$170,000 - $240,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-06',
    sourceName: 'Stripe Careers',
    companyUrl: 'https://stripe.com',
    skills: 'Ruby,Java,Go,Distributed Systems,APIs',
    remoteStatus: 'Hybrid',
  },
  {
    title: 'Marketing Manager',
    companyName: 'HubSpot',
    location: 'Boston, MA',
    description: 'HubSpot is looking for a Marketing Manager to lead demand generation campaigns. You will manage a team of 5, run multi-channel campaigns, and own the marketing budget. 5+ years of B2B marketing experience required.',
    applicationUrl: 'https://hubspot.com/careers/mm-678',
    salary: '$120,000 - $160,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-05',
    sourceName: 'HubSpot Careers',
    companyUrl: 'https://hubspot.com',
    skills: 'Marketing,B2B,Demand Generation,Team Leadership',
    remoteStatus: 'Hybrid',
  },
  // More scam jobs
  {
    title: 'Social Media Evaluator - Work From Home!',
    companyName: '',
    location: 'Remote',
    description: 'Evaluate social media posts from home. $300/day. Easy money. No skills required. Just need a phone. Pay a fee of $25 to activate your account. Contact via telegram @social_eval_hr. We need your passport number for identity verification. Get paid daily.',
    applicationUrl: 'https://bit.ly/sm-eval-2026',
    salary: '$300/day',
    employmentType: 'Part-time',
    postedDate: '2026-08-15',
    sourceName: 'Social Media',
    skills: 'Social Media',
    remoteStatus: 'Remote',
  },
  {
    title: 'Mystery Shopper - Earn $250/Assignment',
    companyName: 'Market Research Associates',
    location: 'Nationwide',
    description: 'Become a mystery shopper. We send you $2000 check, you deposit it and keep $250. Send the rest back via wire transfer. Act now, limited spots available. Contact me at mysteryshopper@gmail.com. Great opportunity, flexible schedule. Make money fast.',
    applicationUrl: 'https://tinyurl.com/mysteryshop22',
    salary: '$250/assignment',
    employmentType: 'Contract',
    postedDate: '2026-08-14',
    sourceName: 'Craigslist',
    skills: 'Mystery Shopping',
    remoteStatus: 'Remote',
  },
  // A few more legitimate jobs
  {
    title: 'Engineering Manager',
    companyName: 'GitLab',
    location: 'Remote',
    description: 'GitLab is hiring an Engineering Manager to lead our CI/CD team. You will manage 8-10 engineers, define technical direction, and ensure delivery of high-quality features. Experience managing remote teams required.',
    applicationUrl: 'https://gitlab.com/careers/em-901',
    salary: '$180,000 - $230,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-04',
    sourceName: 'GitLab Careers',
    companyUrl: 'https://gitlab.com',
    skills: 'Engineering Management,CI/CD,Remote Leadership',
    remoteStatus: 'Remote',
  },
  {
    title: 'Cloud Solutions Architect',
    companyName: 'Salesforce',
    location: 'San Francisco, CA',
    description: 'Salesforce is seeking a Cloud Solutions Architect to design enterprise CRM solutions. You will lead technical discovery sessions, create architecture diagrams, and guide implementation teams. AWS/Azure certifications preferred.',
    applicationUrl: 'https://salesforce.com/careers/csa-234',
    salary: '$160,000 - $220,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-03',
    sourceName: 'Salesforce Careers',
    companyUrl: 'https://salesforce.com',
    skills: 'Cloud Architecture,AWS,Azure,CRM,Salesforce',
    remoteStatus: 'Hybrid',
  },
  {
    title: 'QA Automation Engineer',
    companyName: 'Atlassian',
    location: 'Sydney, Australia',
    description: 'Atlassian is looking for a QA Automation Engineer to improve our testing infrastructure. You will write Selenium and Cypress tests, maintain test suites, and work with developers to improve code quality.',
    applicationUrl: 'https://atlassian.com/careers/qa-auto-567',
    salary: '$110,000 - $150,000 AUD',
    employmentType: 'Full-time',
    postedDate: '2026-08-02',
    sourceName: 'Atlassian Careers',
    companyUrl: 'https://atlassian.com',
    skills: 'QA Automation,Selenium,Cypress,JavaScript',
    remoteStatus: 'Remote',
  },
  {
    title: 'Database Administrator',
    companyName: 'Oracle',
    location: 'Austin, TX',
    description: 'Oracle is hiring a Database Administrator to manage our cloud database services. You will handle database tuning, backup strategies, and migration projects. Oracle DBA certification and 5+ years of experience required.',
    applicationUrl: 'https://oracle.com/careers/dba-890',
    salary: '$125,000 - $170,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-01',
    sourceName: 'Oracle Careers',
    companyUrl: 'https://oracle.com',
    skills: 'Oracle DB,SQL,Database Administration,Cloud',
    remoteStatus: 'Hybrid',
  },
  {
    title: 'Product Design Lead',
    companyName: 'Figma',
    location: 'San Francisco, CA',
    description: 'Figma is hiring a Product Design Lead to shape the future of collaborative design tools. You will lead a team of 4 designers, define design strategy, and create innovative features. Portfolio demonstrating systems-level thinking required.',
    applicationUrl: 'https://figma.com/careers/pdl-123',
    salary: '$175,000 - $240,000',
    employmentType: 'Full-time',
    postedDate: '2026-07-30',
    sourceName: 'Figma Careers',
    companyUrl: 'https://figma.com',
    skills: 'Product Design,Design Systems,Leadership,Figma',
    remoteStatus: 'Hybrid',
  },
  // Duplicate/reposted versions
  {
    title: 'Senior Software Engineer',
    companyName: 'Google',
    location: 'Mountain View, CA',
    description: 'We are looking for a Senior Software Engineer to join our Cloud Platform team. You will design and build scalable distributed systems, work with Kubernetes and GCP, and collaborate with cross-functional teams. Requirements: 5+ years of experience in backend development, proficiency in Go or Java, experience with cloud infrastructure.',
    applicationUrl: 'https://careers.google.com/jobs/results/123457/',
    salary: '$180,000 - $250,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-16',
    sourceName: 'LinkedIn',
    companyUrl: 'https://about.google',
    skills: 'Go,Java,Kubernetes,GCP,Distributed Systems',
    remoteStatus: 'Hybrid',
  },
  {
    title: 'Work From Home Data Entry - $500/Day!',
    companyName: '',
    location: 'Remote',
    description: 'URGENT! We need someone to do simple data entry work from home. Pay is $500 per day guaranteed. No experience needed. You just need a computer and internet. Pay a small registration fee of $50 to get started. Contact me on WhatsApp at +1-555-0123. Send your social security number for tax purposes.',
    applicationUrl: 'https://bit.ly/workfromhome-jobs-new',
    salary: '$500/day guaranteed',
    employmentType: 'Part-time',
    postedDate: '2026-08-16',
    sourceName: 'Facebook',
    skills: 'Data Entry',
    remoteStatus: 'Remote',
  },
  {
    title: 'Remote Software Tester - Easy Work',
    companyName: 'TestTech Global',
    location: 'Remote',
    description: 'Great opportunity to earn money by testing apps. Pay is $200 per test. We need your ID number and credit card details for verification. Pay a processing fee of $100. Call me at 555-1111. No experience needed. Earn money fast.',
    applicationUrl: 'http://suspicious-test-jobs.xyz/apply-v2',
    salary: '$200/test',
    employmentType: 'Contract',
    postedDate: '2026-08-13',
    sourceName: 'Social Media',
    skills: 'Testing',
    remoteStatus: 'Remote',
  },
  {
    title: 'Business Development Associate',
    companyName: 'NexGen Partners',
    location: 'Chicago, IL',
    description: 'Join our team as a Business Development Associate. Responsibilities include prospecting, cold calling, and building client relationships. Self-motivated individuals who thrive in a fast-paced environment will succeed here.',
    applicationUrl: 'https://nexgenpartners.com/jobs/bda-2',
    salary: '$50,000 - $80,000',
    employmentType: 'Full-time',
    postedDate: '2026-08-14',
    sourceName: 'Indeed',
    skills: 'Sales,Business Development,Communication',
    remoteStatus: 'On-site',
  },
];

export function getDemoJobs(): JobRecord[] {
  const jobs: JobRecord[] = rawJobs.map((raw, index) => {
    const id = `job-demo-${index + 1}`;
    const now = new Date().toISOString();
    const skills = raw.skills ? raw.skills.split(',').map(s => s.trim()) : [];

    return {
      id,
      title: raw.title,
      companyName: raw.companyName,
      location: raw.location,
      description: raw.description,
      salary: raw.salary || null,
      employmentType: raw.employmentType || null,
      experienceRequired: null,
      postedDate: raw.postedDate || null,
      applicationUrl: raw.applicationUrl,
      companyUrl: raw.companyUrl || null,
      sourceUrl: raw.sourceUrl || null,
      sourceName: raw.sourceName || 'unknown',
      skills,
      remoteStatus: raw.remoteStatus || null,
      scrapedAt: now,
      riskScore: 0,
      riskLevel: 'LOW',
      riskReasons: [],
      duplicateGroupId: null,
      isReposted: false,
    };
  });

  const withRisk = jobs.map(job => {
    const assessment = calculateRiskScore({
      title: job.title,
      companyName: job.companyName,
      description: job.description,
      applicationUrl: job.applicationUrl,
      companyUrl: job.companyUrl,
      salary: job.salary,
      isReposted: job.isReposted,
      duplicateGroupId: job.duplicateGroupId,
    });
    return {
      ...job,
      riskScore: assessment.score,
      riskLevel: assessment.level,
      riskReasons: assessment.reasons,
    };
  });

  return annotateDuplicates(withRisk);
}

export function getDemoScraperRuns(): ScraperRun[] {
  const now = new Date();
  return [
    {
      id: 'run-1',
      collectorId: 'job-collector-indeed',
      status: 'completed',
      startedAt: new Date(now.getTime() - 300000).toISOString(),
      completedAt: new Date(now.getTime() - 240000).toISOString(),
      recordsFound: 1284,
      validRecords: 1267,
      invalidRecords: 17,
      extractionQuality: 97.8,
      missingTitleCount: 3,
      missingCompanyCount: 8,
      missingLocationCount: 12,
      missingDescriptionCount: 5,
      errorMessage: null,
      createdAt: new Date(now.getTime() - 300000).toISOString(),
    },
    {
      id: 'run-2',
      collectorId: 'job-collector-indeed',
      status: 'completed',
      startedAt: new Date(now.getTime() - 3900000).toISOString(),
      completedAt: new Date(now.getTime() - 3840000).toISOString(),
      recordsFound: 1198,
      validRecords: 1180,
      invalidRecords: 18,
      extractionQuality: 96.2,
      missingTitleCount: 5,
      missingCompanyCount: 10,
      missingLocationCount: 8,
      missingDescriptionCount: 4,
      errorMessage: null,
      createdAt: new Date(now.getTime() - 3900000).toISOString(),
    },
    {
      id: 'run-3',
      collectorId: 'job-collector-indeed',
      status: 'failed',
      startedAt: new Date(now.getTime() - 86400000).toISOString(),
      completedAt: new Date(now.getTime() - 86340000).toISOString(),
      recordsFound: 0,
      validRecords: 0,
      invalidRecords: 0,
      extractionQuality: 0,
      missingTitleCount: 0,
      missingCompanyCount: 0,
      missingLocationCount: 0,
      missingDescriptionCount: 0,
      errorMessage: 'Extraction failed: source layout changed, CSS selectors returned 0 results',
      createdAt: new Date(now.getTime() - 86400000).toISOString(),
    },
    {
      id: 'run-4',
      collectorId: 'job-collector-linkedin',
      status: 'completed',
      startedAt: new Date(now.getTime() - 7200000).toISOString(),
      completedAt: new Date(now.getTime() - 7140000).toISOString(),
      recordsFound: 856,
      validRecords: 841,
      invalidRecords: 15,
      extractionQuality: 98.1,
      missingTitleCount: 2,
      missingCompanyCount: 5,
      missingLocationCount: 7,
      missingDescriptionCount: 3,
      errorMessage: null,
      createdAt: new Date(now.getTime() - 7200000).toISOString(),
    },
  ];
}

export function getDemoScraperHealth(): ScraperHealth {
  return {
    id: 'health-1',
    collectorId: 'job-collector-indeed',
    status: 'HEALTHY',
    lastSuccessfulRun: new Date(Date.now() - 300000).toISOString(),
    lastFailedRun: new Date(Date.now() - 86400000).toISOString(),
    totalRecordsExtracted: 1284,
    extractionQuality: 97.8,
    fieldCompleteness: {
      title: 0.992,
      company: 0.987,
      location: 0.971,
      description: 0.964,
      applicationUrl: 0.958,
    },
    recoveryRate: 100,
    totalHealingEvents: 3,
    averageRecoveryTime: 120,
    updatedAt: new Date().toISOString(),
  };
}

export function getDemoHealingEvents(): HealingEvent[] {
  const now = new Date();
  return [
    {
      id: 'heal-1',
      collectorId: 'job-collector-indeed',
      failureType: 'extraction_degradation',
      failedField: 'title',
      previousRecordCount: 1198,
      failedRecordCount: 0,
      previousCompleteness: 0.98,
      currentCompleteness: 0.04,
      healingStatus: 'recovered',
      startedAt: new Date(now.getTime() - 86400000).toISOString(),
      completedAt: new Date(now.getTime() - 86340000).toISOString(),
      recoveredRecordCount: 1198,
      recoveryPercentage: 100,
      createdAt: new Date(now.getTime() - 86400000).toISOString(),
    },
    {
      id: 'heal-2',
      collectorId: 'job-collector-indeed',
      failureType: 'extraction_degradation',
      failedField: 'company',
      previousRecordCount: 1050,
      failedRecordCount: 420,
      previousCompleteness: 0.97,
      currentCompleteness: 0.45,
      healingStatus: 'recovered',
      startedAt: new Date(now.getTime() - 172800000).toISOString(),
      completedAt: new Date(now.getTime() - 172740000).toISOString(),
      recoveredRecordCount: 1050,
      recoveryPercentage: 100,
      createdAt: new Date(now.getTime() - 172800000).toISOString(),
    },
    {
      id: 'heal-3',
      collectorId: 'job-collector-indeed',
      failureType: 'schema_change',
      failedField: 'location',
      previousRecordCount: 980,
      failedRecordCount: 120,
      previousCompleteness: 0.96,
      currentCompleteness: 0.12,
      healingStatus: 'recovered',
      startedAt: new Date(now.getTime() - 259200000).toISOString(),
      completedAt: new Date(now.getTime() - 259140000).toISOString(),
      recoveredRecordCount: 980,
      recoveryPercentage: 100,
      createdAt: new Date(now.getTime() - 259200000).toISOString(),
    },
  ];
}

export function getDashboardStats() {
  const jobs = getDemoJobs();
  const total = jobs.length;
  const low = jobs.filter(j => j.riskLevel === 'LOW').length;
  const medium = jobs.filter(j => j.riskLevel === 'MEDIUM').length;
  const high = jobs.filter(j => j.riskLevel === 'HIGH').length;

  const jobsOverTime = Array.from({ length: 14 }, (_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - (13 - i));
    const base = 80 + Math.floor(Math.random() * 30);
    return {
      date: date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
      count: base + Math.floor(i * 3),
    };
  });

  const extractionQuality = Array.from({ length: 14 }, (_, i) => {
    const date = new Date();
    date.setDate(date.getDate() - (13 - i));
    let quality = 96 + Math.random() * 4;
    if (i === 5) quality = 12;
    if (i === 6) quality = 89;
    return {
      date: date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
      quality: Math.round(quality * 10) / 10,
    };
  });

  return {
    totalJobs: total,
    lowRisk: low,
    mediumRisk: medium,
    highRisk: high,
    scraperStatus: 'HEALTHY' as const,
    lastSuccessfulRun: new Date(Date.now() - 300000).toISOString(),
    healingEvents: 3,
    recoveryRate: 100,
    jobsOverTime,
    riskDistribution: [
      { level: 'Low Risk', count: low },
      { level: 'Medium Risk', count: medium },
      { level: 'High Risk', count: high },
    ],
    extractionQuality,
  };
}
